/**
 * @module scripts/gen_demo_bytes
 *
 * Dogfood build script: reads `src/wasm/demo.wat`, parses it with binaryen-ts'
 * own Phase 1 WAT parser, encodes it via the Phase 3 binary encoder, and
 * writes the result to `src/wasm/demo.wasm` plus a `src/wasm/demo_bytes.ts`
 * file containing the same bytes as an inline `Uint8Array` literal.
 *
 * This is the Phase 10 demonstration of the toolchain-free embed pipeline:
 * no `wasmtk`, no `wabt`, no `binaryen` npm dependency — just binaryen-ts
 * compiling its own kernel.
 *
 * Run:
 *   deno run --allow-read --allow-write scripts/gen_demo_bytes.ts
 *
 * @license MIT OR Apache-2.0
 */

import { parseWat } from "../src/parser/wat-parser.ts";
import { encodeWasm } from "../src/encoder/wasm-encoder.ts";

const WAT_PATH = new URL("../src/wasm/demo.wat", import.meta.url);
const WASM_PATH = new URL("../src/wasm/demo.wasm", import.meta.url);
const BYTES_TS_PATH = new URL("../src/wasm/demo_bytes.ts", import.meta.url);

const wat = await Deno.readTextFile(WAT_PATH);
const mod = parseWat(wat, "demo.wat");
const bytes = encodeWasm(mod);

await Deno.writeFile(WASM_PATH, bytes);

const hex = Array.from(bytes, (b) => "0x" + b.toString(16).padStart(2, "0")).join(", ");
const ts = `// deno-fmt-ignore-file
/**
 * @module binaryen-ts/wasm/demo_bytes
 *
 * AUTO-GENERATED by \`scripts/gen_demo_bytes.ts\` — do not edit manually.
 *
 * Embedded bytes of \`src/wasm/demo.wat\` after passing through binaryen-ts'
 * own WAT parser (Phase 1) and binary encoder (Phase 3). Loaded by
 * \`src/wasm-runtime.ts\` as the demonstration kernel for Phase 10.
 *
 * Source size: ${bytes.length} bytes.
 *
 * Regenerate:
 *   deno run --allow-read --allow-write scripts/gen_demo_bytes.ts
 *
 * @license MIT OR Apache-2.0
 */

/** WASM bytes for the demo kernel — see {@link ../wasm/demo.wat | demo.wat}. */
export const DEMO_BYTES: Uint8Array = new Uint8Array([${hex}]);
`;
await Deno.writeTextFile(BYTES_TS_PATH, ts);

console.log(`Wrote ${bytes.length} bytes to ${WASM_PATH.pathname}`);
console.log(`Wrote ${BYTES_TS_PATH.pathname}`);
